server:
  port: 8081

spring:
  application:
    name: sport-shop

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sport_shop_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs